require "dotfiles/checker"
require "dotfiles/installer"
require "dotfiles/packages"
require "dotfiles/packages/base"
require "dotfiles/packages/command_line_tools"
require "dotfiles/packages/homebrew"
